server:
  port: 1001


spring:
  application:
    name: TMF_FORUM

  data:
    mongodb:
      database: TMF_FORUM_POC
      port: 27017
      host: localhost

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
  endpoint:
    health:
      show-details:always
